Water Rendering
OpenSAGE/opensage.github.io pull request #50
Opened 2021-07-09 16:55 UTC by VectorIV

Added simple water rendering overview page including figure images.

2021-08-25 14:44 UTC, feliwir commented
@VectorIV could you export the Photoshop files as PNG and include them, since JPG tends to be a bit blurry for lineart. Also please remove the original PSD files if possible. Apart from that it looks great :+1:

2021-08-25 14:44 UTC, feliwir commented on .vs/VSWorkspaceState.json
> +{
Please don't commit your ".vs" folder

2021-10-06 19:38 UTC, Skleni requested changes
Found some typos...otherwise, great work! :)

2021-10-06 19:38 UTC, Skleni commented on posts/water_rendering/water_rendering.md
> +This is done at shader level either via vertex or fragment. Many techniques could be used here including DuDv mapping, bump mapping, nomral mapping, etc.
Typo: nomral

2021-10-06 19:38 UTC, Skleni commented on posts/water_rendering/water_rendering.md
> +**DuDv Mapping** is simply a directoinal distortion map usually derived from a normal map. It only has R and G channels for offsetting U and V vaules of the texture. This creates ripple effect on the
Typos: directoinal, vaules, effect(s?)

2021-10-06 19:38 UTC, Skleni commented on posts/water_rendering/water_rendering.md
> +**Normal Mapping** is an extensive bump map uses for lighting calculation. Having all RGB channels, they are represented as XYZ directions. This creates the illusion of detailed surface without havin
used insted of uses?
...of _a_ detailed surface?

2021-10-06 19:38 UTC, Skleni commented on posts/water_rendering/water_rendering.md
> +At higher level of shadering, I assume one may simulate casutics from the movement of the waves and direction of the lightsource.
Typo: casutics

2021-10-06 19:38 UTC, Skleni commented on posts/water_rendering/water_rendering.md
> +**Fresnel Effect** A principle of reflectivity. Shallow angle = strong reflectivity, steep nagle weak reflectivity. By applying this principle to reflection and refraction rendering, one can improve
Typo: nagle
missing = before weak?

2021-10-06 19:38 UTC, Skleni commented on posts/water_rendering/water_rendering.md
> +With time and afford, you can make it even more convincing but that is a discussion for another time.
effort?

2021-10-06 19:41 UTC, Skleni commented
Why are the roads so broken in the result image? Is this based on the current codebase?

2021-10-18 06:30 UTC, Skleni approved these changes
Thanks!

2021-10-18 10:44 UTC, merged